### ISSUE TITLE
Bioconda plots not up-to-date

### ISSUE THREAD

**Issue by oschwengers** [bioconda/bioconda-plots#2]
Hi,
it seems like the Bioconda package download plots do not get updated anymore.

The GH action is still regularly executed (https://github.com/bioconda/bioconda-plots/actions/runs/2991048431) but due to the logs, there are no changes to commit, so nothing gets updated.

**Comment by daler** [comment]
Good catch, seems fundamentally due to https://github.com/bioconda/bioconda-stats/pull/4 which may be due to a git version issue.

**Comment by oschwengers** [comment]
Sry, this is not meant pushy by any means but just FYI. The package plots are still frozen at July, 10th. Is there any chance/option to update them? Thanks a lot!

**Comment by fxwiegand** [comment]
There is still some issue when the stats are fetched over at https://github.com/bioconda/bioconda-stats/ so it might be best to open another issue there where someone might take care of it. Like you mentioned yourself before, the workflow in this repository is still running but simply has nothing to commit due to the problem over at bioconda-stats so there's not much i can do about it here sadly 😅

**Comment by oschwengers** [comment]
Oh I see, sorry, my fault. I'll open an issue over there and link it to this one. Thanks for the fast response!

**Comment by aliciaaevans** [comment]
Original issue was fixed by https://github.com/bioconda/bioconda-plots/pull/3. And the more recent unrelated but similar issues have been fixed also.
